//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivoFijo.DatabaseModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN()
        {
            this.ADMINISTRARs = new HashSet<ADMINISTRAR>();
        }
    
        public int IDBIEN { get; set; }
        public int IDASIGNADO { get; set; }
        public string NOMBRE { get; set; }
        public string COLOR { get; set; }
        public int IDMARCA { get; set; }
        public int IDTIPO { get; set; }
        public int IDESTADO { get; set; }
        public int VIDAUTIL { get; set; }
        public decimal PORCENTAGEDEPRECIACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMINISTRAR> ADMINISTRARs { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
