//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivoFijo.DatabaseModule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class activo_fijoEntities : DbContext
    {
        public activo_fijoEntities()
            : base("name=activo_fijoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRAR> ADMINISTRARs { get; set; }
        public virtual DbSet<BIEN> BIENs { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<MARCA> MARCAs { get; set; }
        public virtual DbSet<TIPO> TIPOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
