CREATE DATABASE ACTIVO_FIJO;
USE ACTIVO_FIJO;

CREATE TABLE ACTIVO_FIJO.USUARIO (
  IDUSUARIO INT AUTO_INCREMENT NOT NULL UNIQUE,
  USUARIO   VARCHAR(11)        NOT NULL UNIQUE,
  CLAVE     VARCHAR(11)        NOT NULL,
  Nombre    VARCHAR(100)       NOT NULL,
  DUI       CHAR(10)            NOT NULL UNIQUE
);

CREATE TABLE ACTIVO_FIJO.BIEN (
  IDBIEN                 INT AUTO_INCREMENT          NOT NULL UNIQUE,
  IDASIGNADO             INT                         NOT NULL UNIQUE,
  NOMBRE                 VARCHAR(50)                 NULL,
  COLOR                  VARCHAR(20)                 NULL,
  IDMARCA                INT                         NOT NULL,
  IDTIPO                 INT                         NOT NULL,
  PORCENTAGEDEPRECIACION FLOAT(15, 2) DEFAULT '0.00' NOT NULL
);

CREATE TABLE ACTIVO_FIJO.ADMINISTRAR (
  IDUsuario   INT                         NOT NULL,
  IDBien      INT                         NOT NULL,
  FECHACOMPRA DATE,
  Costo       FLOAT(15, 2) DEFAULT '0.00' NOT NULL,
  CANTIDAD    INT
);

CREATE TABLE ACTIVO_FIJO.MARCA (
  IDMARCA     INT AUTO_INCREMENT UNIQUE,
  NOMBREMARCA VARCHAR(50)
);

CREATE TABLE ACTIVO_FIJO.TIPO (
  IDTIPO     INT AUTO_INCREMENT UNIQUE,
  NOMBRETIPO VARCHAR(50)
);

##PRIMARY KEYS
ALTER TABLE ACTIVO_FIJO.USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO);
ALTER TABLE ACTIVO_FIJO.BIEN ADD CONSTRAINT PK_BIEN PRIMARY KEY (IDBIEN);
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR ADD CONSTRAINT PK_ADMINISTRAR PRIMARY KEY (IDUsuario, IDBien);
ALTER TABLE ACTIVO_FIJO.MARCA ADD CONSTRAINT PK_MARCA PRIMARY KEY (IDMARCA);
ALTER TABLE ACTIVO_FIJO.TIPO ADD CONSTRAINT PK_TIPO PRIMARY KEY (IDTIPO);


##FOREIGN KEY
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR ADD FOREIGN KEY (IDUsuario) REFERENCES USUARIO(IDUSUARIO);
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR ADD FOREIGN KEY (IDBien) REFERENCES BIEN(IDBIEN);
ALTER TABLE ACTIVO_FIJO.BIEN ADD FOREIGN KEY (IDTIPO) REFERENCES MARCA(IDMARCA);
ALTER TABLE ACTIVO_FIJO.BIEN ADD FOREIGN KEY (IDTIPO) REFERENCES TIPO(IDTIPO);