CREATE DATABASE ACTIVO_FIJO;
DROP DATABASE  ACTIVO_FIJO
USE ACTIVO_FIJO;
CREATE SCHEMA ACTIVO_FIJO;

CREATE TABLE ACTIVO_FIJO.USUARIO (
  IDUSUARIO INT IDENTITY (1, 1),
  USUARIO   VARCHAR(25)  NOT NULL UNIQUE,
  CLAVE     VARCHAR(11)  NOT NULL,
  Nombre    VARCHAR(100) NOT NULL,
  DUI       CHAR(10)     NOT NULL UNIQUE
);

CREATE TABLE ACTIVO_FIJO.BIEN (
  IDBIEN                 INT IDENTITY (1, 1),
  IDASIGNADO             INT                           NOT NULL UNIQUE,
  NOMBRE                 VARCHAR(50)                   NULL,
  COLOR                  VARCHAR(20)                   NULL,
  IDMARCA                INT                           NOT NULL,
  IDTIPO                 INT                           NOT NULL,
  IDESTADO               INT                           NOT NULL,
  VIDAUTIL               INT                           NOT NULL,
  PORCENTAGEDEPRECIACION DECIMAL(15, 2) DEFAULT '0.00' NOT NULL
);

CREATE TABLE ACTIVO_FIJO.ADMINISTRAR (
  IDUsuario         INT                           NOT NULL,
  IDBien            INT                           NOT NULL,
  FECHAADQUISISCION DATE,
  FECHACOMPRA       DATE,
  Costo             DECIMAL(15, 2) DEFAULT '0.00' NOT NULL,
  CANTIDAD          INT
);

CREATE TABLE ACTIVO_FIJO.ESTADO (
  IDEstado INT IDENTITY (1, 1),
  ESTADO   VARCHAR(50)
);

CREATE TABLE ACTIVO_FIJO.MARCA (
  IDMARCA     INT IDENTITY (1, 1),
  NOMBREMARCA VARCHAR(50)
);

CREATE TABLE ACTIVO_FIJO.TIPO (
  IDTIPO     INT IDENTITY (1, 1),
  TIPO VARCHAR(50)
);

--PRIMARY KEYS
ALTER TABLE ACTIVO_FIJO.USUARIO
  ADD CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO);
ALTER TABLE ACTIVO_FIJO.BIEN
  ADD CONSTRAINT PK_BIEN PRIMARY KEY (IDBIEN);
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR
 ADD CONSTRAINT PK_ADMINISTRAR PRIMARY KEY (IDUsuario, IDBien);
ALTER TABLE ACTIVO_FIJO.MARCA
  ADD CONSTRAINT PK_MARCA PRIMARY KEY (IDMARCA);
ALTER TABLE ACTIVO_FIJO.TIPO
  ADD CONSTRAINT PK_TIPO PRIMARY KEY (IDTIPO);
ALTER TABLE ACTIVO_FIJO.ESTADO
  ADD CONSTRAINT  PK_ESTADO PRIMARY KEY (IDEstado);

--FOREIGN KEY
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR
  ADD FOREIGN KEY (IDUsuario) REFERENCES ACTIVO_FIJO.USUARIO (IDUSUARIO);
ALTER TABLE ACTIVO_FIJO.ADMINISTRAR
  ADD FOREIGN KEY (IDBien) REFERENCES ACTIVO_FIJO.BIEN (IDBIEN);
ALTER TABLE ACTIVO_FIJO.BIEN
  ADD FOREIGN KEY (IDTIPO) REFERENCES ACTIVO_FIJO.MARCA (IDMARCA);
ALTER TABLE ACTIVO_FIJO.BIEN
  ADD FOREIGN KEY (IDTIPO) REFERENCES ACTIVO_FIJO.TIPO (IDTIPO);
ALTER TABLE ACTIVO_FIJO.BIEN
    ADD FOREIGN KEY (IDESTADO) REFERENCES ACTIVO_FIJO.ESTADO(IDEstado);

INSERT INTO ACTIVO_FIJO.USUARIO(USUARIO, CLAVE, Nombre, DUI) VALUES('CBRC Contabilidad', 'CBRC2019', 'Roxana', '0000000001');
INSERT INTO ACTIVO_FIJO.MARCA(NOMBREMARCA) VALUES ('SOME');
INSERT INTO ACTIVO_FIJO.TIPO(TIPO.TIPO) VALUES ('ANOTHER SOME');
INSERT INTO ACTIVO_FIJO.ESTADO(ESTADO) VALUES ('Nuevo');
INSERT INTO ACTIVO_FIJO.ESTADO(ESTADO) VALUES ('Usado');
SELECT * FROM ACTIVO_FIJO.USUARIO;
SELECT * FROM ACTIVO_FIJO.MARCA;
SELECT * FROM ESTADO;
SELECT * FROM TIPO;
SELECT * FROM BIEN;
SELECT * FROM ADMINISTRAR;
SELECT * FROM BIEN INNER JOIN ADMINISTRAR ON BIEN.IDBIEN = ADMINISTRAR.IDBien;